### ISSUE TITLE
How to replace loadjs.done

### ISSUE THREAD

**Issue by wgehner** [muicss/johnnydepp#2]
With loadjs, somewhere in the <head> of a page I could start something early, e.g.

axios.get('/news/items.json').then(function(resp) {
         news = resp.data
         loadjs.done('news')
})// fetch

And then somewhere in the <body> of the page use the result, e.g.

loadjs.ready('news', function() {
      tag.render(news)
})

How would I do that with johnnydepp?

**Comment by wgehner** [comment]
Without loadjs, my example would probably written like this:
In html head:
axios.get('/news/items.json').then(function(resp) {
news = resp.data
newsLoaded()
})// fetch
In html body:
function newsLoaded(){
tag.render(news)
}
But the browser would not be able to find the function in the fetch. I see this as a dependency problem. Imho, functions that are inline are just as important as ones in external js.

**Comment by amorey** [comment]
The `.done()` method has been implemented in JohnnyDepp v0.0.3:
https://www.npmjs.com/package/johnnydepp
