### ISSUE TITLE
Here is example of depp js use in a wild:

### ISSUE THREAD

**Issue by cekvenich** [muicss/johnnydepp#5]
I wanted to show an example of depp use in the wild/www. Our framework at www.metabake.org is used in a few commercial and open source apps - and it leverages depp.js. The first step we do in an html page is load depp definitions, as a tool belt of libs to use. Here are our mentions of deep, the first link is a bit of a shrine to depp.js:
- http://github.com/metabake/metaCake/tree/master/toolBelt
- http://github.com/metabake/metaCake/blob/master/toolBelt/toolBelt.js
- http://metabake.github.io/mbakeDocs/#/toolBelt
- http://blog.metabake.org/posts/depp-intro
Ideally all the links here are reachable from http://MetaBake.org

**Comment by amorey** [comment]
Awesome! Happy to hear that depp is being used successfully in the wild!

**Comment by cekvenich** [comment]
oops, I moved it:
- https://github.com/metabake/mbake/tree/master/zBrowserServices/toolBelt
